apiVersion: v1
kind: Service
metadata:
	name: getway-service
	labels:
		name: getway-service
		app: microservice
spec:
	type: LoadBalancer
	ports: 
		- port: 80
		  targetPort: 80
		  nodePort: 30010
	selector:
		app: getway
		type: microservice