apiVersion: apps/v1
kind: Deployment
metadata: 
	name: getway-deploy
	labels: 
		name: getway-deploy
		app: microservice
spec:
	replicas: 1
	selector: 
		matchLabels:
			app: getway
			type: microservice
	template:
		metadata:
			name: getway-pod
			labels: 
				app: getway
				type: microservice
		spec:
			containers:
				- name: getway-app
				  image: rrmora02/serviciosapigateway:latest
				  ports: 
					- containerPorts: 80