apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:4.4.6
      command:
      - /bin/bash
      - -c
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "rrmora02"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "rrmora022023$12345"
      ports:
        - containerPort: 27017