apiVersion: v1
kind: Pod
metadata:
	name: mongo-pod
	labels: 
		app: microservice-libreria
		name: mongo-pod
spec:
	containers:
	- name: mongo
	  image: mongo:5.0.22
	  command:
	  - /bin/bash
	  - -c
	  env:
	  - name: MONGO_INITDB_ROOT_USERNAME
	    value: "rrmora02"
	  - name: MONGO_INITDB_ROOT_PASSWORD
		value: "$rrmora022023"
	  ports: 
		- containerPorts: 27017