apiVersion: apps/v1
kind: Deployment
metadata:
	name: mssql-deploy
	labels: 
		name: mssql-deploy
		app: microservice-seguridad
spec:
	replicas: 1
	selector: 
		matchLabels:
			app: microservice-seguridad
			name: mssql-pod
	template:
		metadata:
			name: sqlserver-pod
			labels: 
				app: microservice-seguridad
				name: mssql-pod
		spec:
			containers:
			- name: mssql
			  image: mcr.microsoft.com/mssql/server
			  command:
			  - /bin/bash
			  - -c
			  env:
			  - name: ACCEPT_EULA
				value: "Y"
			  - name: SA_PASSWORD
				value: "$rrmora022023"
			  ports: 
				- containerPorts: 1433